<?php namespace Redaxscript\Template; ?>

<!-- base -->

<?php echo Tag::base(); ?>

<!-- title -->

<?php echo Tag::title(Helper::getRegistry('fullRoute') ? Helper::getTitle() : Helper::getSetting('title')); ?>

<!-- meta -->

<?php echo Tag::meta()
	->init()
	->append('charset', Helper::getSetting('charset'))
	->append(['name' => 'author', 'content' => Helper::getSetting('author')])
	->append(['name' => 'generator', 'content' => Helper::getLanguage('_package')['name'] . ' ' . Helper::getLanguage('_package')['version']])
	->append(['name' => 'description', 'content' => Helper::getRegistry('fullRoute') ? Helper::getDescription() : Helper::getSetting('description')])
	->append(['name' => 'keywords', 'content' => Helper::getRegistry('fullRoute') ? Helper::getKeywords() : Helper::getSetting('keywords')])
	->append(['name' => 'robots', 'content' => Helper::getRegistry('fullRoute') ? Helper::getRobots() : 'all'])
	->append(['name' => 'viewport', 'content' => 'width=device-width'])
	->append(['name' => 'theme-color', 'content' => '#ef5350'])
	->append(['name' => 'msapplication-navbutton-color', 'content' => '#ef5350'])
	->append(['name' => 'apple-mobile-web-app-status-bar-stylecontent', 'content' => '#ef5350'])
	->append(['name' => 'msvalidate.01', 'content' => '9904AD2FB469A0860172008547D3BD27'])
	->append(['name' => 'google-site-verification', 'content' => 'EH-bQWFd2zRU3xt-BB6aDUxCQTyCJGgZDJGajYo7TVc']); ?>

<!-- link -->

<?php echo Tag::link()
	->init()
	->append(['href' => Helper::getRegistry('fullRoute') ? Helper::getCanonical() : Helper::getRegistry('root'), 'rel' => 'canonical'])
	->append(['href' => 'data:image/png;base64,', 'rel' => 'shortcut icon'])
	->appendFile(
	[
		'https://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700&amp;subset=' . Helper::getSubset(),
		'https://fonts.googleapis.com/css?family=Amatic+SC:700&amp;subset=' . Helper::getSubset(),
		'templates/redaxmedia/dist/styles/redaxmedia.min.css'
	])
	->rewrite(
	[
		'../../../../templates' => '../../templates',
		'../../../../modules' => '../../modules'
	])
	->concat(); ?>

<?php echo Tag::link()->init('admin'); ?>

<!-- head script -->

<?php echo Tag::script()
	->init('head')
	->prependFile('assets/scripts/init.js')
	->transportVar('rs', Helper::getTransport())
	->concat(); ?>