<?php namespace Redaxscript\Template; ?>

<!-- header -->

<div class="rs-wrapper-header">
	<header id="header" class="rs-header">

		<!-- title -->

		<?php if (Helper::getSetting('title')): ?>
			<h1 class="rs-title-header">
				<a href="<?php echo Helper::getRegistry('root'); ?>">
					<?php echo Helper::getSetting('title'); ?>
				</a>
			</h1>
		<?php endif; ?>

		<!-- description -->

		<?php if (Helper::getSetting('description')): ?>
			<span class="rs-text-header" title="<?php echo Helper::getSetting('description'); ?>"><?php echo Helper::getSetting('description'); ?></span>
		<?php endif; ?>
	</header>
</div>
