<?php namespace Redaxscript\Template; ?>

<?php $categories = Tag::categoryRaw()->where('status', 1)->findMany(); ?>
<?php $articles = Tag::articleRaw()->where('status', 1)->orderByDesc('date')->findMany(); ?>

<!-- homepage -->

<article id="content" class="rs-content">
	<?php foreach ($articles as $article): ?>
		<?php $category = $categories[$article->category - 2];  ?>
		<div class="rs-wrapper-timeline" data-category="<?php echo $category->alias; ?>">
			<section class="rs-section-timeline">
				<h2 class="rs-title-timeline">
					<a href="<?php echo $article->alias; ?>"><?php echo $article->title; ?></a>
				</h2>
				<p class="rs-text-timeline"><?php echo strip_tags($article->text); ?></p>
				<span class="rs-text-date"><?php echo date(Tag::getSetting('date'), strtotime($article->date)); ?></span>
			</section>
		</div>
	<?php endforeach; ?>
</article>
