<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Helper::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass('rs-is-'); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'admin/head.phtml',
			'redaxmedia/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<body class="rs-body">
		<?php $body = Tag::partial(
		[
			'redaxmedia/header.phtml',
			'redaxmedia/main.phtml',
			'admin/script.phtml',
			'redaxmedia/script.phtml'
		]); ?>
		<?php echo Tag::partial(
        [
            'admin/panel.phtml',
            'admin/dashboard.phtml'
        ]); ?>
		<?php echo $body; ?>
	</body>
</html>
