<?php namespace Redaxscript\Template; ?>

<!-- timeline -->

<?php if (Helper::getRegistry('categoryId')): ?>
	<main class="rs-main rs-has-timeline">
		<?php echo include('redaxmedia/helper/badge.php'); ?>
		<?php echo Tag::partial('redaxmedia/timeline.phtml'); ?>
	</main>

<!-- else default -->

<?php else: ?>
	<main id="main" class="rs-main">

		<!-- bad response -->

		<?php if (Helper::getResponseCode() === 404): ?>
			<?php echo Tag::partial('redaxmedia/error.phtml'); ?>

		<!-- else content -->

		<?php else: ?>
			<?php echo Tag::partial('redaxmedia/content.phtml'); ?>
		<?php endif; ?>
	</main>
<?php endif; ?>
