<?php namespace Redaxscript\Template; ?>

<!-- homepage -->

<?php if (!Tag::getRegistry('fullRoute')): ?>
	<main class="rs-main rs-has-timeline">
		<?php echo Tag::partial('templates/redaxmedia/homepage.phtml'); ?>
	</main>

<!-- else default -->

<?php else: ?>
	<main id="main" class="rs-main">

		<!-- error -->

		<?php if (Tag::getRegistry('contentError')): ?>
			<?php echo Tag::partial('templates/redaxmedia/error.phtml'); ?>

		<!-- else content -->

		<?php else: ?>
			<?php echo Tag::partial('templates/redaxmedia/content.phtml'); ?>
		<?php endif; ?>
	</main>
<?php endif; ?>