<?php namespace Redaxscript\Template; ?>

<!-- timeline -->

<article id="content" class="rs-content">
	<?php foreach ($timelineArray as $eventArray): ?>
		<div class="rs-wrapper-timeline" data-category="<?php echo $eventArray['categoryArray']['alias']; ?>">

            <!-- section -->

			<section class="rs-section-timeline">
				<h2 class="rs-title-timeline">
					<a href="<?php echo Tag::getRegistry('rewriteRoute') . $eventArray['articleArray']['route']; ?>"><?php echo $eventArray['articleArray']['title']; ?></a>
				</h2>
				<p class="rs-text-timeline"><?php echo $eventArray['articleArray']['text']; ?></p>
				<span class="rs-text-date"><?php echo $eventArray['articleArray']['date']; ?></span>
			</section>
		</div>
	<?php endforeach; ?>
</article>
