language: php

php:
- 7.2

before_install:
- composer self-update
- composer global require hirak/prestissimo

install:
- composer install
- nvm install 9
- npm install --global grunt-cli
- npm install

script:
- grunt

notifications:
 email:
 - info@redaxmedia.com