language: php

php:
- 7.1

before_install:
- composer global require hirak/prestissimo

install:
- composer self-update
- composer install
- nvm install 6
- npm install --global ied
- npm install --global grunt-cli
- ied install

script:
- grunt

notifications:
 email:
 - info@redaxmedia.com